### PR TITLE
Updating Forms Samples to beta8

### PR DESCRIPTION
**Pull request by lothrop**
This doesn't work yet. Does anyone have the time to have a look and tell me what the problem is?

### CODE REVIEW

**Comment by lothrop** [comment]
By "work" I mean compile.

**Comment by PeterBurke** [comment]
I will be looking at it this weekend, give me several days.

**Comment by lothrop** [comment]
Thanks!

**Comment by lothrop** [comment]
@martijn00 Could you please have a look?

**Comment by martijn00** [comment]
@lothrop the sample was already broken some time, so i guess it need some more fixes then only updating the packages.

**Comment by PeterBurke** [comment]
I committed these changes. Originally I was responsible for all development on the samples.

I am now working on the samples to get them working again.

Since Martijn reports they were broken sometime back, it does not matter that they are still broken.

Changes are mainly name changes to bring into line with changes in the core MvvmCross.

I will now proceed to get them working.

**Pull request merged**
