### PR TITLE
Four Samples including w81 tested with a page matching VM

### PR DESCRIPTION
**Pull request by PeterBurke**
1. Rebuilt WindowStore as w81, Will later remove WindowStore
2. Added FirstPage to match ViewModel FirstViewModel
3. Tested all four targets, all show a Form, however presentation needs fine tuning per target
4. WindowStore is a Windows8 term, For VS2013 Xamarin released w81 and wp81 targets. Might add a wp81 target later (non silverlight windows phone)
5.Added a solution file so that solution can be opened with VS 2013. Not fully tested as it requires setting up a full Xamarin testing environment. VS 2015 has a new set of simulators for Android, Windows Phone and Windoes tablet. I would not want to go back to VS2013!
6. This request incorporates #9 now closed.

Next PR will remove WindowStore. Tip use VS extension "Code Compare" to see what changed.

Next PR will likewise rename the WindowStore FormPresenter to W81.

Next PR will add an about box to the FirstPage to demonstrate MvvMCross commands and navigation.

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks! I am wondering about the WindowsStore and W81 stuff what would be correct. Which one is the most uptodate of those 2? What about Windows Universal?

**Comment by PeterBurke** [comment]
I will answer this one when I get back from my workout and supper.

Sent from my Windows Phone
________________________________

**Comment by PeterBurke** [comment]
Hi Martijn

A couple of days back [jonstoneman](https://github.com/MvvmCross/MvvmCross/issues/1055#issuecomment-120588434) commented that he happy to see WindowsStore removed from MvvmCross. He thought that NuGet would install it for Windows 8.0 Apps but install Windows Common for 8.1 Apps.

I was unsure if the FormPresenter was actually linking to the correct target at the time as there were a lot of issues getting it working.

I have now determined that it works against the Windows Common.

The other concern that I have is that the name of the FormPresenter and the Samples should not confuse people. Now it seems that Microsoft intended the Windows Store to only supply metro/modern apps, but they have changed their mind about this. The new push is for Universal Apps.

They intend these to run on all devices and on a hybrid device like the surface they should run equally as well on the desktop and the start screen. If you load say outlook on the start screen it works one way, but if you load it on the desktop, windows puts a frame around it with the usual buttons and expanders etc.

So as of May 1 when Xamarin / Microsoft released two new targets being w81 and wpa81 (windows phone application 8.1) both of which can be obtained from the Windows Store. These standards are partially universal, but when Windows 10 is out, there is another big step toward universality, in fact w81 and wpa81 could quickly disappear.

Xamarin advertised on their web site for people interested in working with their version of the universal app that presumably will also be cross-platform. I have not heard much more about it.

So my argument is not to use the Window Store term, but to use w81 and wpa81 and later uwp.

as an aside it seems that to build a truly compliant w81 or uwp App there are a lot of things we have not considered like how the App registers itself with Windows Search. But then this is not really an MvvMCross issue.

Futher reading:

https://dev.windows.com/en-us/windows-apps

**Comment by martijn00** [comment]
Thanks for explaining! I based the name "WindowsStore" on the example of James Montemagno here: https://github.com/jamesmontemagno/Hanselman.Forms But indeed the correct way to go would be universal.

**Comment by martijn00** [comment]
@PeterBurke I found out that there are errors in the project:

`The type 'System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'``

Can you look into that?

**Comment by PeterBurke** [comment]
Ah Scott Hanselman!

Yes I admire Scott. The number of times I have found something on his blog that has helped me is uncountable.

I think you have done very well also, because you are willing to share and get others involved. I on the other hand have been in the situation where a customer is paying me for something and I have problems I need to solve but I know that I cannot rely on anyone including vendors to provide help in a reasonable time frame, so to often I do not reach out and involve others.

**Comment by PeterBurke** [comment]
Hi Martijn

In relation to the unreferenced assembly, I get that happening to me all the time when working with Xamarin, and not just with this project. I had it first time I pulled down Cheesebaron some months back. I had it yesterday afternoon while testing.

Yesterday it occurred in the Example.ios project. I had not had my Mac Mini turned on for several days and had ignored that project completely.

To test Example.ios project I first need to set it as the start up project. This changes what Visual Studio shows in the debug box and following boxes.
ios
You can see above there are three boxes following the Debug box. I have highlighted the last of these and sometimes it becomes unset and simply reads "Device" and I get that error. Now the second box "Solution Platforms" is set to iPhoneSimulator, but the simulator device is not set. Once I set it, the compile error goes away.

What is happening is that Visual Studio compiles into CIL and sends it across to the iOS Build Host for linking into assemblies. On the iOS and Android platforms, Xamarin have their own core .NET Framework assemblies, this is how PCL works. When you look into these core assemblies they are not all one to one with Windows, they often combine assemblies into one larger assembly.

I suspect though that when the Device for the iPhoneSimulator has not been selected then the build host does not report the correct error.

**Comment by martijn00** [comment]
I am not sure what you mean by this, but what i do is simply compile the Forms presenter projects. I didn't notice this before so i suspect somewhere in your changes it got in. There are quite some topics on this error in combination with Xamarin on the Xamarin Forums. Maybe you could take a look there to see if this can be solved. We can't put out new Nugets if this is not compiling.

**Comment by Cheesebaron** [comment]
Also please remove the HotTuna and MvvmCross nuget packages, they are super annoying when updating packages.

**Comment by PeterBurke** [comment]
Hi Martijn

Can you tell me which project has the missing reference error, I am assuming Example.ios?

**Comment by PeterBurke** [comment]
Hi Martijn

I guess you will not be able to respond to my question straight away. In the mean time someone else has sent me something to look at in the Android example.

The problem for me is that I don't have the issue, so I would like you to help me out here by providing more details.

Generally though a missing reference like the one you reported can be solved simply by adding a reference to the missing assembly. In your case that would be to System.ObjectModel.

I searched for an assembly that would match and I came up with:
```
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.ObjectModel.dll
```
The location of this assembly suggests that it is a Facade for Xamarin.iOS i.e. it is simply a redirection to the Xamarin assembly for iOS that provides System.ComponentModel.INotifyPropertyChanged. The reason the issue would be intermittent is that its functionality has been merged into another assembly and does not need a separate reference.

If this fixes the problem for you, it is already in my fork and you will get it in the next PR, but you are welcome to update the main branch ahead of this.

**Comment by martijn00** [comment]
@PeterBurke The problem with the references is described here: https://github.com/dotnet/roslyn/issues/970

**Pull request merged**
