### PR TITLE
Updated nuspecs for VS2015

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by PeterBurke** [comment]
Thanks Martijn
I will pull to my local fork.

I am taking a few days off to attend to business. I have researched and prepared some work on using the Xamarin UI Test. The way this test works is that you include a component in the App that allows the UI Test App to interact with the pages. So for example if the test were to enter text into an entry box and click a button, it can do that via control id's that are compiled into the page rather than having to know the exact location on the page and send events via the event loop. I understand that UI Test can also take a screen shot and save it, making it easy to recover visual verification of the presentation on individual devices.

The other thing that I was researching was how to use Search Engine Optimisation SEO techniques so that Google and other search engines show results from this site. In order to use SEO you need to create meta data. This typically for a given article means a synopsis allowing the SE to give greater weight to hits from within the synopsis, plus a list of key words or terms.

It is not possible to do this with the GitHub Mark Down, also it is not clear if Goggle and others actually index Wiki content as the Robots file seems to exclude that.

However there is a way to do it via the https://github.com/MvvmCross/mvvmcross.github.io site. I notice that you were the last to update this site. It is supposed to be a Web Site where you add real HTML pages. There are tools that are better than Mark Down for generating the HTML.

Right now though this site seems to be a fork of another site and it looks like you are trying to set up a blog?

Just wondering what is going on there?

**Comment by PeterBurke** [comment]
Reading up on [Jekyll](http://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/) I navigate to http://mvvmcross.com/ and I can see a very simple web site published by editing content at  https://github.com/MvvmCross/mvvmcross.github.io 

Very simple at this stage, and just the two blog posts. Readers of the Blog can respond via disqus.

So what I would be looking to add would be to rename the "Blog" menu link "Home" and then add other menu links etc. building it up to become a more sophisticated CMS style site.

In order to enable SEO I would need another Menu link that would take the user to a page that would have an expandable hierarchical menu on the right with an article page on the right.

**Comment by martijn00** [comment]
Hi Peter,

We opened a new official MvvmCross blog there. It's a standard Jekyll blog. We should be able to rename and add new items here: https://github.com/MvvmCross/mvvmcross.github.io/blob/master/_layouts/default.html#L49

I have to look into how Jekyll supports the kind of changes you want, but i think it might be a good idea! We could link the wiki of the separate sub-repos in there so it is more clear what we are working on in total.

If you want you can make a PR to change some stuff there. Otherwise i'll look into this somewhere next week.

**Comment by PeterBurke** [comment]
Thanks Martijn

I don't mind if you get to first! I think http://www.tournemille.com/blog/How-to-create-data-driven-navigation-in-Jekyll/ is the way to go. The hierarchical menu uses Yaml a system based on data files forming the menu plus static HTML pages. This allows you to quickly restructure the hierarchy as more content becomes available.

What I have in mind is that most of the wiki content will be moved to static pages under the io site, but even these will be auto generated using one of the extended mark down tools that allow you add meta data.

Back at the original wiki, except for the home and custom side bar will be removed and linkages will be to the content in the io site.

**Pull request merged**
