### PR TITLE
Upgrades references to MvvmCross (4.0.0.0-beta1) to (4.0.0.0-beta3). …

### PR DESCRIPTION
**Pull request by PeterBurke**
…Some Beta1 references had strong names, the Beta3 versions do not.

### CODE REVIEW

**Comment by martijn00** [comment]
Seems good to merge, but there are some conflicts. Can you resolve them first.

**Comment by PeterBurke** [comment]
OK

Actually the only files I wanted in the PR were the 5 csproj and 5 packages.config files because I have not made any changes to the c# code. However Tomasz a couple of months back made come c# changes in one file that were not were not in my GitHib Repo. So I simply downloaded that one separately, but GitHub seems to think that there are conflicts.

Also there is now one more change, that is to the NuSpec updating version numbers of dependencies and also renaming this to 4.0.0-beta3.

It all runs OK.

So give me a few more hours and I should have a new PR.

Can you point me at the GitHub that would allow me to pull the current file from the remote master into my remote fork and so that file will not be in the next PR. Don't worry if you can't answer within 60 seconds.

**Comment by martijn00** [comment]
You can update this PR. I would add this repo as remote to yours, and hit merge on the head of this one. That will merge all the latest stuff in and probably fix merge conflicts.

**Comment by martijn00** [comment]
Should it be closed?

**Comment by PeterBurke** [comment]
Hmmm

Sent from my Windows Phone
________________________________

**Comment by martijn00** [comment]
@PeterBurke I've merged it manually now in #26 I can merge that if no more changes are required.

**Comment by PeterBurke** [comment]
Thanks Martijn

**Pull request merged**
