### PR TITLE
Forms.Presenters and Samples now linked by NuGet

### PR DESCRIPTION
**Pull request by PeterBurke**
CHANGE ITEMS
=============
- Minor restructure to remove WindowStore replaced by W81

- Added code provided by Huynh Khac Thao for Android to allow back and reopen

- Upgraded the sample to include an About page to demonstrate MvvMCross navigation

- W81 target was not showing a toolbar, added platform specific coding to fix

- Upgraded MvvMCross package references to 4.0.0.0-Alpha9, upgraded Xamarin reference to latest stable

- Re-factored NuGet package references reducing the number of dependencies on Core MvvMCross to just 3

- Examples no longer link to Form Presenters via project reference and use NuGet package reference

- Restructured the MvvMCross-Forms NuSpec dependencies on Core MvvMCross. MvvmCross has a package called starter pack. All content is in that package. We do not want that package for the Forms.Presnter examples as these already contain content and the additional content will break and confuse.

**Note for Reviewers**
I created a variant of pack.bat called dev_pack.bat. This publishes the FormsPresenters to a local file directory instead of to the Web. You need to tell visual Studio about the new source: Tools > Manage NuGet Packages > Package Manager Settings. Here you can create additional source locations. I called mine 'local'

When you need to add the package to a project in Visual Studio change the the source location like so:

image

I would expect you to send the package to NeGet as I do not have the API Key.

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks, i'll test it later today.

**Comment by flashvnn** [comment]
Ping pong, any news for new replease and nutget update?

**Comment by martijn00** [comment]
New release will be when it is ready.

**Comment by Cheesebaron** [comment]
@flashvnn if you want to hurry up the process, then involve yourself. Questions like "when will it be released" are not helpful at all...

**Comment by PeterBurke** [comment]
Hi Martijn

I have a load of additional work in the pipeline. I will not combine it into this PR unless you give the green light - that would be because it would let you skip having to test this PR with the same detail.

The changes are visible from [my fork](https://github.com/PeterBurke/MvvmCross-Forms/) and basically involve restructuring the Samples area to allow for multiple samples.

There are now two samples the second being a copy of the first but with the Pages being written in XAML instead of c#.

Additionally I have written a "wall of words" Wiki. The Wiki area in Git is actually separate from the code area so can be pushed up separately. I have not pushed it up yet and you will get a chance to review. It explains about the objective "to provide a source where Xamarin developers can fast track into Xamarin with MvvmCross framework and plug-ins", "how to write compatible XAML" etc.

Also you previously recommended that I not spend time on testing under VS 2013, This actually is only about a hour setting up and testing, so I might as well do that tomorrow again in case there are compile errors etc. that are making your life hard. Note: all SLN files have been demoted to VS2013 format. VS2015 does not seem to care about that and leaves them in that state.

**Comment by martijn00** [comment]
I am OK with merging this in so you might as well combine that one in. I need to find some time to look more into this stuff, but i am happy that you are helping out!

**Comment by martijn00** [comment]
@PeterBurke I've merged this in and did a test if it runs, there where some errors, which i fixed. Please merge my changes back into your repo. Thanks for your help!

**Comment by PeterBurke** [comment]
Thanks Martijn

I went to the Origin and looked at the [changes you applied](https://github.com/MvvmCross/MvvmCross-Forms/commit/118a2c4c66ca9d7b1540cbbd94c73c73743f3239) and tried to apply them directly to my local branch. Virtually all of them were in CSPROJ files and I find that merging can be very tricky with those files.

Mostly though the changes could be ignored, e.g. changing upper/lower case of a Guid or a change to a file I have deleted. Still some of the changes would have caused issues and I applied those. I will also do my own build on VS2013 just to be sure before doing the Push and PR from now on.

Thanks also for sending the Forms Presenter NuPkg's up to NuGet.org.

**Comment by Cheesebaron** [comment]
Use Git to merge the files instead of doing it by hand?

**Comment by PeterBurke** [comment]
Hi

Good idea except that my local branch has a large number of changes compared to my fork on githib. Due to the fixes yesterday the fork also has in the other direction mostly in Csproj files.

Got is not very good at merging / understanding Msbuild so you need to be very careful when doing a merge with those files.

But the number of changes back the other way were small I could see them in the diff and it was easy to apply directly to my local. Also I will be proving everything loads on a clean VS2013 box from now on and builds first time and I know what to look for. 😎

Sent from my Windows Phone
________________________________

**Comment by Cheesebaron** [comment]
No you are just managing your repository incorrectly.

**Comment by martijn00** [comment]
What i normally do to prevent issue's like this, is that i keep my own master as a clean copy of the MvvmCross master. Then i start working on new branch and make all the changes on it. Then make a PR to the MvvmCross master. When that gets merged in, i merge it back to my own master.

**Comment by PeterBurke** [comment]
Maybe I  actually spent the last eighteen months contracting in a Bank that used Git locally as well as SpecFlow advanced testing to block any updates that broke anything. Multiple teams multiple projects  teams making changes that broke others etc. You had to push and pull almost every hour and sometimes got would hand you a merge problem that was mind blowing.

Sent from my Windows Phone
________________________________

**Pull request merged**
